services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: needapp-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: ${DATABASE_URL}
      JwtSettings__SecretKey: ${JWT_SECRET_KEY}
      GoogleSettings__ClientId: ${GOOGLE_CLIENT_ID}
      Cloudinary__CloudName: ${CLOUDINARY_CLOUD_NAME}
      Cloudinary__ApiKey: ${CLOUDINARY_API_KEY}
      Cloudinary__ApiSecret: ${CLOUDINARY_API_SECRET}
      SmtpSettings__SenderEmail: ${SMTP_SENDER_EMAIL}
      SmtpSettings__AppPassword: ${SMTP_APP_PASSWORD}
      SmtpSettings__LogoUrl: ${SMTP_LOGO_URL}
      SmtpSettings__AppUrl: ${SMTP_APP_URL}
      GeminiSettings__ApiKey: ${GEMINI_API_KEY}
      Recaptcha__SecretKey: ${RECAPTCHA__SECRET_KEY}