// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using NeedApp.Infrastructure.Persistence;

#nullable disable

namespace NeedApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420000001_AddMessageEditAndPin")]
    partial class AddMessageEditAndPin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
